//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOAP_CONSOLE_VELIB.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IServiceVelib")]
    public interface IServiceVelib {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVelib/getCities", ReplyAction="http://tempuri.org/IServiceVelib/getCitiesResponse")]
        string[] getCities();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVelib/getCities", ReplyAction="http://tempuri.org/IServiceVelib/getCitiesResponse")]
        System.Threading.Tasks.Task<string[]> getCitiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVelib/getStations", ReplyAction="http://tempuri.org/IServiceVelib/getStationsResponse")]
        string[] getStations(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVelib/getStations", ReplyAction="http://tempuri.org/IServiceVelib/getStationsResponse")]
        System.Threading.Tasks.Task<string[]> getStationsAsync(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVelib/getAvailableBikes", ReplyAction="http://tempuri.org/IServiceVelib/getAvailableBikesResponse")]
        int getAvailableBikes(string city, string station, int delay);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVelib/getAvailableBikes", ReplyAction="http://tempuri.org/IServiceVelib/getAvailableBikesResponse")]
        System.Threading.Tasks.Task<int> getAvailableBikesAsync(string city, string station, int delay);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceVelibChannel : SOAP_CONSOLE_VELIB.ServiceReference1.IServiceVelib, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceVelibClient : System.ServiceModel.ClientBase<SOAP_CONSOLE_VELIB.ServiceReference1.IServiceVelib>, SOAP_CONSOLE_VELIB.ServiceReference1.IServiceVelib {
        
        public ServiceVelibClient() {
        }
        
        public ServiceVelibClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceVelibClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceVelibClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceVelibClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] getCities() {
            return base.Channel.getCities();
        }
        
        public System.Threading.Tasks.Task<string[]> getCitiesAsync() {
            return base.Channel.getCitiesAsync();
        }
        
        public string[] getStations(string city) {
            return base.Channel.getStations(city);
        }
        
        public System.Threading.Tasks.Task<string[]> getStationsAsync(string city) {
            return base.Channel.getStationsAsync(city);
        }
        
        public int getAvailableBikes(string city, string station, int delay) {
            return base.Channel.getAvailableBikes(city, station, delay);
        }
        
        public System.Threading.Tasks.Task<int> getAvailableBikesAsync(string city, string station, int delay) {
            return base.Channel.getAvailableBikesAsync(city, station, delay);
        }
    }
}
